### ISSUE TITLE
Yugioh simulator developer chat. / 愚公移山模拟器开发人员聊天。

### ISSUE THREAD

**Issue by PixelatedProphet** [sbl1996/ygo-agent#1]
We are interested in your project and would like you to join our dev chat. We have devs from Salvation, Edopro, Dueling Book, Dueling Nexus, and others here.

我们对您的项目很感兴趣，希望您能加入我们的开发聊天室。我们这里有来自 Salvation、Edopro、Dueling Book、Dueling Nexus 和其他公司的开发人员。
https://discord.gg/wUjrTS4

**Comment by sbl1996** [comment]
I am already in the chat :)
